name: Selenium Tawk Bot

on:
  workflow_dispatch:

jobs:
  selenium:
    runs-on: ubuntu-latest

    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome, Tor, and Privoxy
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable tor privoxy

      - name: Configure and Start Tor and Privoxy
        run: |
          # Configure Privoxy to route through Tor SOCKS5 proxy
          echo "forward-socks5t / 127.0.0.1:9050 ." | sudo tee -a /etc/privoxy/config
          
          # Restart services to apply configurations
          sudo systemctl restart tor
          sudo systemctl restart privoxy
          
          # Wait a few seconds for Tor to connect to the network
          sleep 15
          

      - name: Show versions
        run: |
          python --version
          google-chrome --version
          tor --version
          
      - name: Remove old ChromeDriver
        run: |
          sudo rm -f /usr/bin/chromedriver
          sudo rm -f /usr/local/bin/chromedriver
          
      - name: Run Selenium
        run: |
          python -u tawk_headless.py
          
      - name: Archive Production Screenshots
        if: always() # Runs even if the script fails or crashes
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: screenshots/ # Uploads all captured .png files
          if-no-files-found: warn
